DELIMITER $$

SET @saved_sql_mode = @@sql_mode
$$
SET @@sql_mode = 'STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION'
$$
CREATE TRIGGER `payment_date`
	BEFORE INSERT
	ON payment
	FOR EACH ROW
SET NEW.payment_date = NOW()
$$

DELIMITER ;